import Foundation

enum L10n {
    static func text(_ key: String, _ language: AppLanguage) -> String {
        let resource = language == .zh ? "zh-Hans" : "en"
        guard
            let path = Bundle.main.path(forResource: resource, ofType: "lproj"),
            let bundle = Bundle(path: path)
        else {
            return fallback[key] ?? key
        }
        return bundle.localizedString(
            forKey: key,
            value: fallback[key],
            table: "Localizable"
        )
    }

    private static let fallback: [String: String] = [
        "app.name": "Zaki",
        "sidebar.life": "Life",
        "sidebar.dashboard": "Overview",
        "sidebar.inventory": "Inventory",
        "sidebar.assets": "Assets",
        "sidebar.expenses": "Recurring Costs",
        "sidebar.tools": "Tools",
        "sidebar.todos": "To-Dos",
        "sidebar.reminders": "Reminders",
        "sidebar.runningProjects": "Running Projects",
        "sidebar.files": "Files",
        "sidebar.aiHot": "AI News",
        "sidebar.browser": "Browser",
        "file.title": "Files",
        "file.search": "Search files and folders",
        "file.searching": "Searching…",
        "file.refresh": "Refresh",
        "file.back": "Back",
        "file.forward": "Forward",
        "file.up": "Enclosing Folder",
        "file.newFile": "New File",
        "file.newFolder": "New Folder",
        "file.rename": "Rename",
        "file.copy": "Copy",
        "file.move": "Move",
        "file.paste": "Paste",
        "file.pasteMove": "Move Here",
        "file.trash": "Move to Trash",
        "file.trash.done": "Moved to Trash",
        "file.undo": "Undo",
        "file.open": "Open",
        "file.quickLook": "Quick Look",
        "file.reveal": "Reveal in Finder",
        "file.view": "View",
        "file.view.list": "List",
        "file.view.icons": "Icons",
        "file.sort": "Sort",
        "file.sort.name": "Name",
        "file.sort.size": "Size",
        "file.sort.kind": "Kind",
        "file.sort.modified": "Date Modified",
        "file.sort.ascending": "Ascending",
        "file.sort.descending": "Descending",
        "file.hidden.show": "Show Hidden Files",
        "file.hidden.hide": "Hide Hidden Files",
        "file.favorites": "Favorites",
        "file.favorite.add": "Add to Favorites",
        "file.favorite.remove": "Remove from Favorites",
        "file.locations": "Locations",
        "file.devices": "Devices",
        "file.location.home": "Home",
        "file.location.desktop": "Desktop",
        "file.location.downloads": "Downloads",
        "file.location.documents": "Documents",
        "file.location.pictures": "Pictures",
        "file.chooseFolder": "Choose Folder…",
        "file.loading": "Loading…",
        "file.empty.title": "This Folder Is Empty",
        "file.empty.body": "Drop files here or create a folder.",
        "file.empty.search.title": "No Results",
        "file.empty.search.body": "Try another name or location.",
        "file.empty.selection.title": "No Selection",
        "file.empty.selection.body": "Select an item to see its details.",
        "file.permission.title": "Folder Access Needed",
        "file.permission.body": "Allow access to view and manage this folder.",
        "file.permission.retry": "Try Again",
        "file.permission.chooseOther": "Choose Another Folder",
        "file.error.title": "Couldn't Complete the Operation",
        "file.error.partial.title": "Some Items Were Skipped",
        "file.error.partial.body": "Completed items were kept. Review the failed items and try again.",
        "file.error.unavailable": "This location is no longer available.",
        "file.confirm.trash.title": "Move to Trash?",
        "file.confirm.trash.item": "This item will be moved to the Trash.",
        "file.confirm.trash.multiple": "The selected items will be moved to the Trash.",
        "file.conflict.title": "An Item with This Name Already Exists",
        "file.conflict.body": "Choose how to handle the duplicate item.",
        "file.conflict.replace": "Replace",
        "file.conflict.keepBoth": "Keep Both",
        "file.conflict.skip": "Skip",
        "file.conflict.cancel": "Cancel",
        "file.conflict.applyAll": "Apply to All",
        "file.column.name": "Name",
        "file.column.size": "Size",
        "file.column.kind": "Kind",
        "file.column.modified": "Date Modified",
        "file.detail.title": "Details",
        "file.detail.name": "Name",
        "file.detail.kind": "Kind",
        "file.detail.created": "Created",
        "file.detail.size": "Size",
        "file.detail.modified": "Modified",
        "file.detail.path": "Path",
        "file.detail.items": "Items",
        "file.folder.name": "Folder Name",
        "file.file.name": "File Name",
        "running.title": "Running Projects",
        "running.search": "Search projects, ports, or processes",
        "running.refresh": "Refresh",
        "running.scanning": "Scanning listening ports…",
        "running.updated": "Last updated",
        "running.summary.projects": "projects",
        "running.summary.ports": "listening ports",
        "running.section.projects": "Development Projects",
        "running.section.other": "Other Listening Processes",
        "running.showOther": "Show other listening processes",
        "running.projectBadge": "PROJECT",
        "running.open": "Open",
        "running.open.help": "Open in the default browser",
        "running.reveal": "Reveal in Finder",
        "running.copyAddress": "Copy address",
        "running.stop": "Stop",
        "running.stop.help": "Stop this development service",
        "running.stop.confirm.title": "Stop this service?",
        "running.stop.confirm.body": "A termination request will be sent to",
        "running.error": "Operation failed",
        "running.empty.title": "No Listening Ports",
        "running.empty.body": "Start a local development service, then refresh this page.",
        "aihot.channel.label": "Channel",
        "aihot.channel.selected": "Selected",
        "aihot.channel.hotTopics": "Trending",
        "aihot.channel.daily": "Daily",
        "aihot.refresh": "Refresh",
        "aihot.refresh.wait": "Please wait before refreshing again",
        "aihot.refresh.available": "Refresh available",
        "aihot.loading": "Loading AI news…",
        "aihot.loadingMore": "Loading more…",
        "aihot.loadMore": "Load More",
        "aihot.filters.window": "Time Range",
        "aihot.filters.category": "Category",
        "aihot.window.24h": "24 Hours",
        "aihot.window.7d": "7 Days",
        "aihot.category.all": "All Categories",
        "aihot.category.ai-models": "AI Models",
        "aihot.category.ai-products": "AI Products",
        "aihot.category.industry": "Industry",
        "aihot.category.paper": "Research",
        "aihot.category.tip": "Tips & Opinions",
        "aihot.search.placeholder": "Search AI news",
        "aihot.search.clear": "Clear Search",
        "aihot.search.minimum": "Enter at least 2 characters to search.",
        "aihot.selected.title": "Selected AI News",
        "aihot.hotTopics.title": "Trending Now",
        "aihot.hot.sourceCount": "Independent sources",
        "aihot.hot.sources": "Sources",
        "aihot.score": "Score",
        "aihot.original": "Original",
        "aihot.open.aihot": "Open on AI HOT",
        "aihot.attribution.default": "AI HOT",
        "aihot.daily.title": "AI Daily",
        "aihot.daily.archive": "Past Reports",
        "aihot.daily.archive.empty": "No archived reports",
        "aihot.daily.generated": "Generated",
        "aihot.daily.lead": "Lead Story",
        "aihot.daily.flashes": "News Flashes",
        "aihot.error.title": "Couldn't Load AI HOT",
        "aihot.error.cached": "Showing the last successful results",
        "aihot.retry": "Retry",
        "aihot.dismiss": "Dismiss",
        "aihot.empty.selected.title": "No Selected News",
        "aihot.empty.selected.body": "Try another time range, category, or search.",
        "aihot.empty.hotTopics.title": "No Trending Topics",
        "aihot.empty.hotTopics.body": "AI HOT has no multi-source topics to show right now.",
        "aihot.empty.daily.title": "No Daily Report",
        "aihot.empty.daily.body": "The latest AI daily report is not available yet.",
        "todos.title": "To-Dos",
        "todos.new": "New To-Do",
        "todos.empty.title": "No to-dos yet",
        "todos.empty.body": "Type above and press Return to add one.",
        "todos.open": "To-Do",
        "todos.completed": "Completed",
        "todos.quickAdd": "New to-do",
        "todos.quickAdd.placeholder": "Type a to-do and press Return",
        "todos.quickAdd.hint": "Press Return to add",
        "todos.markOpen": "Mark as Open",
        "todos.markCompleted": "Mark as Completed",
        "todos.delete": "Delete",
        "reminders.title": "Reminders",
        "reminders.new": "New Reminder",
        "reminders.active": "Active",
        "reminders.paused": "Paused",
        "reminders.completed": "Completed",
        "reminders.empty.title": "No reminders yet",
        "reminders.empty.body": "Create a reminder for anything important.",
        "reminders.next": "Next",
        "reminders.every": "Every",
        "reminders.once": "Once",
        "reminders.repeat": "Repeat",
        "reminders.pause": "Pause",
        "reminders.resume": "Resume",
        "reminders.edit": "Edit",
        "reminders.try": "Try",
        "reminders.try.help": "Show this reminder now",
        "reminders.try.failed": "Couldn't Show Reminder",
        "reminders.try.failed.body": "Check notification permission and try again.",
        "reminders.delete": "Delete",
        "reminders.delete.confirm": "Delete this reminder?",
        "editor.new": "New Reminder",
        "editor.edit": "Edit Reminder",
        "editor.content": "Reminder",
        "editor.content.placeholder": "Take a moment to stretch",
        "editor.interval": "Interval",
        "editor.hours": "Hours",
        "editor.minutes": "Minutes",
        "editor.seconds": "Seconds",
        "editor.mode": "Mode",
        "editor.enabled": "Enable immediately",
        "common.cancel": "Cancel",
        "common.save": "Save",
        "common.create": "Create",
        "browser.address": "Search or enter website name",
        "browser.newTab": "New Tab",
        "browser.start": "Start Page",
        "browser.favorites": "Favorites",
        "browser.bookmarks": "Bookmarks",
        "browser.back": "Back",
        "browser.forward": "Forward",
        "browser.reload": "Reload",
        "browser.home": "Start Page",
        "browser.bookmark": "Add Bookmark",
        "browser.unbookmark": "Remove Bookmark",
        "browser.dark": "Website Dark Mode",
        "common.archive": "Archive",
        "common.close": "Close",
        "common.daysBefore": "days before",
        "common.edit": "Edit",
        "common.notes": "Notes",
        "dashboard.title": "Life Overview",
        "dashboard.overview": "Today at a glance",
        "dashboard.charts": "Signals & Forecasts",
        "dashboard.actions": "Needs Attention",
        "dashboard.inventory": "Inventory Review",
        "dashboard.inventory.expiring": "Expiring within 30 days",
        "dashboard.review.again": "Review Again",
        "dashboard.review.completed": "This week is complete",
        "dashboard.review.completed.body": "Counted items are up to date.",
        "dashboard.review.disabled": "Weekly review is off",
        "dashboard.review.disabled.body": "Turn it on in Settings to keep inventory current.",
        "dashboard.review.due": "Inventory review is due",
        "dashboard.review.due.body": "Check remaining quantities; skipped items keep their previous values.",
        "dashboard.review.scheduled": "Next review is scheduled",
        "dashboard.review.scheduled.body": "Zaki will remind you at the weekly review time.",
        "dashboard.review.start": "Start Review",
        "dashboard.notifications.off": "Notifications are off",
        "dashboard.notifications.off.body": "Enable notifications to receive review and payment reminders.",
        "dashboard.financial": "Financial Assets",
        "dashboard.financial.current": "Current Financial Value",
        "dashboard.financial.unrealized": "Unrealized P/L",
        "dashboard.financial.stale": "Prices to update",
        "dashboard.durable": "Durable Assets",
        "dashboard.durable.daily": "Combined daily cost",
        "dashboard.durable.warranty": "Warranties expiring",
        "dashboard.expenses": "Recurring Costs",
        "dashboard.expenses.monthly": "Monthly Recurring Cost",
        "dashboard.expenses.annual": "Annual estimate",
        "dashboard.expenses.next30": "Due in 30 days",
        "dashboard.todos": "Open To-Dos",
        "dashboard.todos.completed": "completed",
        "dashboard.gauge.review": "Review Progress",
        "dashboard.gauge.inventoryHealth": "Inventory Health",
        "dashboard.gauge.priceFreshness": "Price Freshness",
        "dashboard.chart.allocation": "Financial Allocation",
        "dashboard.chart.allocation.empty": "No valued positions yet",
        "dashboard.chart.assetType": "Asset Type",
        "dashboard.chart.expenseForecast": "30-Day Payment Forecast",
        "dashboard.chart.expenseForecast.empty": "No payments due in the next 30 days",
        "dashboard.chart.period": "Period",
        "dashboard.chart.amount": "Amount",
        "dashboard.accessibility.open": "Open details",
        "inventory.title": "Household Inventory",
        "inventory.add": "Add Item",
        "inventory.items": "Household Items",
        "inventory.search": "Search items",
        "inventory.empty.title": "No household items",
        "inventory.empty.body": "Add daily supplies and start tracking their remaining quantities.",
        "inventory.noResults.title": "No matching items",
        "inventory.noResults.body": "Try clearing the current search or filters.",
        "inventory.filters": "Filters",
        "inventory.filters.clear": "Clear Filters",
        "inventory.filter.all": "All",
        "inventory.filter.status": "Status",
        "inventory.filter.location": "Location",
        "inventory.filter.low": "Low stock",
        "inventory.filter.expiring": "Expiring soon",
        "inventory.filter.unreviewed": "Not reviewed",
        "inventory.status.low": "Low stock",
        "inventory.status.ok": "In stock",
        "inventory.status.expiring": "Expiring",
        "inventory.status.unreviewed": "Not reviewed",
        "inventory.status.notRecorded": "Not recorded",
        "inventory.details.title": "Item Details",
        "inventory.details.open": "Open Details",
        "inventory.lastCount": "Last updated",
        "inventory.expiration": "Expiration",
        "inventory.expiration.enable": "Track an expiration date",
        "inventory.quantityPrice.update": "Update Quantity & Price",
        "inventory.editor.details": "Item Details",
        "inventory.field.name": "Name",
        "inventory.field.location": "Storage Location",
        "inventory.field.unit": "Unit",
        "inventory.field.lowThreshold": "Low-stock threshold",
        "inventory.field.initialQuantity": "Initial quantity",
        "inventory.field.quantity": "Quantity",
        "inventory.field.expiration": "Nearest expiration date",
        "inventory.unit.default": "item",
        "inventory.price.initialUnitPrice": "Initial unit price",
        "inventory.price.history": "Price History",
        "inventory.price.records": "Price Records",
        "inventory.price.latest": "Latest Unit Price",
        "inventory.price.lowest": "Historical Low",
        "inventory.price.lowest.detail": "Lowest recorded unit price",
        "inventory.price.average": "Historical Average",
        "inventory.price.average.detail": "Average of all recorded unit prices",
        "inventory.price.trend": "Price Trend",
        "inventory.price.unitPrice": "Unit Price",
        "inventory.price.purchaseDate": "Update Date",
        "inventory.price.previous": "Previous unit price",
        "inventory.price.required": "Enter a unit price to count this item.",
        "inventory.price.correct": "Correct Latest Price",
        "inventory.price.empty.title": "No price history",
        "inventory.price.empty.body": "Update quantity and price together to see historical lows and price trends.",
        "inventory.price.empty.compact": "Update quantity and price to start comparing.",
        "inventory.price.comparison.insufficient": "More history needed",
        "inventory.price.comparison.lowest": "New historical low",
        "inventory.price.comparison.cheaper": "below previous average",
        "inventory.price.comparison.equal": "Same as previous average",
        "inventory.price.comparison.expensive": "above previous average",
        "inventory.review.title": "Weekly Inventory Review",
        "inventory.review.start": "Start Review",
        "inventory.review.again": "Review Again",
        "inventory.review.complete": "Complete Review",
        "inventory.review.completed": "Review complete",
        "inventory.review.completed.body": "This week's counted items are up to date.",
        "inventory.review.due": "Review household supplies",
        "inventory.review.due.body": "Update confirmed quantities and prices; skip anything you did not count.",
        "inventory.review.skipHint": "Skipped items keep their previous quantity and price.",
        "inventory.review.skip": "Skip this item",
        "inventory.review.previous": "Previous",
        "inventory.review.notEntered": "Not counted this week",
        "inventory.review.schedule": "Weekly Review Schedule",
        "inventory.review.reminder": "Remind me every week",
        "inventory.review.weekday": "Weekday",
        "inventory.review.time": "Time",
        "assets.title": "Personal Assets",
        "assets.section": "Asset View",
        "assets.summary": "Asset Overview",
        "assets.durable": "Durable Assets",
        "assets.financial": "Financial Assets",
        "assets.add": "Add Asset",
        "assets.durable.add": "Add Durable Asset",
        "assets.durable.items": "Durable Assets",
        "assets.durable.empty.title": "No durable assets",
        "assets.durable.empty.body": "Track purchases such as computers, cameras, furniture, and appliances.",
        "assets.durable.total": "Purchase Total",
        "assets.durable.total.detail": "Total amount invested in active durable assets",
        "assets.durable.dailyCost": "Daily Cost",
        "assets.durable.dailyCost.detail": "Combined purchase cost per day held",
        "assets.durable.warranty": "Warranty",
        "assets.durable.warranty.detail": "Warranties expiring within 30 days",
        "assets.financial.add": "Add Financial Asset",
        "assets.financial.items": "Financial Assets",
        "assets.financial.empty.title": "No financial assets",
        "assets.financial.empty.body": "Add an asset, then record trades and a manual price.",
        "assets.financial.currentValue": "Current Value",
        "assets.financial.currentValue.detail": "Based on the latest manually entered prices",
        "assets.financial.unrealized": "Unrealized P/L",
        "assets.financial.unrealized.detail": "Current value minus remaining cost basis",
        "assets.financial.stale": "Prices to Update",
        "assets.financial.stale.detail": "Prices not updated in the last 7 days",
        "assets.editor.details": "Asset Details",
        "assets.field.name": "Name",
        "assets.field.code": "Code",
        "assets.field.type": "Type",
        "assets.purchaseDate": "Purchase Date",
        "assets.purchasePrice": "Purchase Price",
        "assets.estimatedValue": "Estimated Value",
        "assets.valuation": "Track a current estimate",
        "assets.valuationUpdated": "Valuation updated",
        "assets.warranty": "Warranty",
        "assets.warranty.enable": "Track warranty",
        "assets.warranty.end": "Warranty End Date",
        "assets.warranty.until": "Covered until",
        "assets.warranty.expired": "Warranty expired",
        "assets.averageCost": "Average Cost",
        "assets.latestPrice": "Latest Price",
        "assets.price.update": "Update Price",
        "assets.price.date": "Price Date",
        "assets.price.stale": "Price is stale",
        "assets.transaction.add": "Add Transaction",
        "assets.transaction.kind": "Transaction",
        "assets.transaction.date": "Trade Date",
        "assets.quantity": "Quantity",
        "assets.unitPrice": "Unit Price",
        "assets.fee": "Fee",
        "assets.realized": "Realized P/L",
        "assets.unrealized.short": "Unrealized",
        "assets.type.stock": "Stock",
        "assets.type.fund": "Fund",
        "assets.type.deposit": "Deposit",
        "assets.type.cash": "Cash",
        "assets.type.cryptocurrency": "Cryptocurrency",
        "assets.type.other": "Other",
        "assets.transaction.buy": "Buy",
        "assets.transaction.sell": "Sell",
        "assets.transaction.oversold": "The sale exceeds the available holding.",
        "assets.transaction.invalid": "Enter a valid quantity, price, and fee.",
        "expenses.title": "Recurring Costs",
        "expenses.summary": "Spending Overview",
        "expenses.add": "Add Recurring Cost",
        "expenses.items": "Recurring Costs",
        "expenses.empty.title": "No recurring costs",
        "expenses.empty.body": "Track loans, subscriptions, property fees, and other regular payments.",
        "expenses.monthly": "Monthly Equivalent",
        "expenses.monthly.detail": "Normalized across all active recurring costs",
        "expenses.annual": "Annual Estimate",
        "expenses.annual.detail": "Projected recurring cost for one year",
        "expenses.next30Days": "Next 30 Days",
        "expenses.next30Days.detail": "Payments scheduled within 30 days",
        "expenses.monthlyEquivalent": "Monthly equivalent",
        "expenses.nextDue": "Next due",
        "expenses.remaining": "Remaining payments",
        "expenses.ongoing": "Ongoing",
        "expenses.autoRenew": "Auto-renews",
        "expenses.reminder": "Reminder",
        "expenses.pause": "Pause",
        "expenses.status.active": "Active",
        "expenses.status.paused": "Paused",
        "expenses.status.upcoming": "Due soon",
        "expenses.editor.details": "Cost Details",
        "expenses.editor.schedule": "Billing Schedule",
        "expenses.editor.reminder": "Reminder",
        "expenses.field.name": "Name",
        "expenses.field.amount": "Amount",
        "expenses.field.cycle": "Cycle",
        "expenses.field.interval": "Every",
        "expenses.field.anchorDate": "First or Anchor Date",
        "expenses.field.endDate.enable": "Has an end date",
        "expenses.field.endDate": "End Date",
        "expenses.field.enabled": "Active",
        "expenses.reminder.enable": "Remind me before payment",
        "expenses.reminder.leadDays": "Remind me",
        "expenses.cycle.day": "Day",
        "expenses.cycle.week": "Week",
        "expenses.cycle.month": "Month",
        "expenses.cycle.year": "Year",
        "notification.inventory.review": "Time for your weekly inventory review.",
        "notification.expense.due": "A recurring expense is due soon.",
        "settings.general": "General",
        "settings.life": "Life",
        "settings.inventoryReview": "Weekly inventory review",
        "settings.inventoryReview.enabled": "Remind me every week",
        "settings.inventoryReview.weekday": "Weekday",
        "settings.inventoryReview.time": "Time",
        "settings.backup": "Local backup",
        "settings.backup.description": "Export all Zaki data as JSON",
        "settings.backup.export": "Export Backup…",
        "settings.shortcuts": "Shortcuts",
        "settings.about": "About",
        "settings.appearance": "Appearance",
        "settings.system": "System",
        "settings.light": "Light",
        "settings.dark": "Dark",
        "settings.language": "Language",
        "settings.chinese": "简体中文",
        "settings.english": "English",
        "settings.browserDark": "Dark website adaptation",
        "settings.globalShortcut": "Show or hide Zaki",
        "settings.shortcutHint": "Click the recorder, then press a shortcut.",
        "settings.notification": "Notifications",
        "settings.notification.allowed": "Allowed",
        "settings.notification.denied": "Not allowed",
        "settings.notification.unknown": "Not requested",
        "settings.openSystemSettings": "Open System Settings",
        "settings.version": "Version",
        "status.migrated": "Your reminders and bookmarks were imported.",
        "status.permissionDenied": "Notifications are disabled. Enable them in System Settings.",
        "status.shortcutUnavailable": "That shortcut is unavailable; ⌘⇧H is active instead.",
        "status.backupExported": "Backup exported."
    ]
}
